spring:
  application:
    name: java11-and-gradle
  
  datasource:    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  
server:  port: 8090

logging:  file:    name: /var/tmp/logs/${spring.application.name}/${spring.application.name}
  level:    root: info
    '[poc.springboot]': debug